collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.3882734
color:
  saturation: 0.3854297
  brandStrength: 0.6106678
  lightness: 0.2329749
  brandColors:
    - '#151516'
    - '#F0D9BB'
    - '#B2BFB5'
    - '#4A5B65'
    - '#778791'
  rhythmicContrast: 0.01131351
layout_spectrum: 0.2021102
name: Geislerprojects
