name: Geislerprojects
favicon: null
layout_spectrum: 0.2021102
typography_spectrum: 0.3882734
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: GEISLER PROJECTS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151516'
    - '#F0D9BB'
    - '#B2BFB5'
    - '#4A5B65'
    - '#778791'
  brandStrength: 0.6106678
  lightness: 0.2329749
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
