title: GEISLER PROJECTS
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0.7956989
  lightness: 0.2329749
  brandColors:
    - '#151516'
    - '#F0D9BB'
    - '#B2BFB5'
    - '#4A5B65'
    - '#778791'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Geislerprojects
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3882734
layout_spectrum: 1
